### ISSUE TITLE
Error [ERR_REQUIRE_ESM] with vite/3.1.5 darwin-x64 node-v16.17.1

### ISSUE THREAD

**Issue by andreacfromtheapp** [feat-agency/vite-plugin-webfont-dl#16]
Hi :)

I'm a weirdo and I like to keep my very few npm pkgs/dependencies up to date.

I've just updated Vite to 3.1.5 and now I get this error when running ```vite``` with ```npm run dev```. You may want to look into it, going forward. It seems a pretty easy fix and a breaking change with Vite from now on.

```
failed to load config from /Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/vite.config.js
error when starting dev server:
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite-plugin-webfont-dl/dist/index.mjs not supported.
Instead change the require of /Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite-plugin-webfont-dl/dist/index.mjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/vite.config.js:33:37)
    at Object._require.extensions.<computed> [as .js] (file:///Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite/dist/node/chunks/dep-49b3b5ea.js:63524:24)
    at loadConfigFromBundledFile (file:///Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite/dist/node/chunks/dep-49b3b5ea.js:63532:21)
    at loadConfigFromFile (file:///Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite/dist/node/chunks/dep-49b3b5ea.js:63400:34)
    at async resolveConfig (file:///Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite/dist/node/chunks/dep-49b3b5ea.js:63017:28)
    at async createServer (file:///Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite/dist/node/chunks/dep-49b3b5ea.js:62083:20)
    at async CAC.<anonymous> (file:///Users/gacallea/ProjectsandIdeas/Sites/gacallea.info/node_modules/vite/dist/node/cli.js:700:24)
```

cheers and thank you for this amazing plugin :)

**Comment by 0xb4lint** [comment]
Hi @gacallea!
I cannot reproduce this error with the latest vite version. :/
Could you please help me with your Node version?

**Comment by 0xb4lint** [comment]
I'm sorry, it's in the title 🤦 

I've tried with Node 16, but with no success, I'll keep trying...

**Comment by 0xb4lint** [comment]
I've deployed [v3.1.3](https://github.com/feat-agency/vite-plugin-webfont-dl/releases/tag/v3.1.3) with package type changes.
Could you please check it?

**Comment by andreacfromtheapp** [comment]
> I've deployed [v3.1.3](https://github.com/feat-agency/vite-plugin-webfont-dl/releases/tag/v3.1.3) with package type changes. Could you please check it?

seems to have done the trick :)

ref: https://github.com/gacallea/elm_vite_tailwind_template

thank you so much!
