### ISSUE TITLE
"protocol mismatch" when set `HTTPS_PROXY` to socks5 protocl

### ISSUE THREAD

**Issue by Discreater** [feat-agency/vite-plugin-webfont-dl#24]
Below is my font config
```ts
...
webfontDownload([
  'https://fonts.googleapis.com/css2?family=Bitter&family=Noto+Serif+SC&display=swap',
]),
...
```
When I use socks5 proxy:
```sh
HTTPS_PROXY=socks5://192.168.50.161:10808 pnpm build

> qsync@0.0.0 build /home/alkaid/source/QSync
> vue-tsc && vite build

vite v4.0.4 building for production...
✓ 72 modules transformed.
rendering chunks (1)...node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AssertionError [ERR_ASSERTION]: protocol mismatch
    at Object.request (/home/alkaid/source/QSync/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:521:14)
    at dispatchHttpRequest (file:///home/alkaid/source/QSync/node_modules/.pnpm/axios@1.3.2/node_modules/axios/lib/adapters/http.js:414:21)
    at new Promise (<anonymous>)
    at http (file:///home/alkaid/source/QSync/node_modules/.pnpm/axios@1.3.2/node_modules/axios/lib/adapters/http.js:122:10)
    at Axios.dispatchRequest (file:///home/alkaid/source/QSync/node_modules/.pnpm/axios@1.3.2/node_modules/axios/lib/core/dispatchRequest.js:51:10)
    at Axios.request (file:///home/alkaid/source/QSync/node_modules/.pnpm/axios@1.3.2/node_modules/axios/lib/core/Axios.js:142:33)
    at Function.wrap [as request] (file:///home/alkaid/source/QSync/node_modules/.pnpm/axios@1.3.2/node_modules/axios/lib/helpers/bind.js:5:15)
    at CssLoader.load (file:///home/alkaid/source/QSync/node_modules/.pnpm/vite-plugin-webfont-dl@3.6.0_vite@4.0.4/node_modules/vite-plugin-webfont-dl/dist/index.js:46:34)
    at CssLoader.loadAll (file:///home/alkaid/source/QSync/node_modules/.pnpm/vite-plugin-webfont-dl@3.6.0_vite@4.0.4/node_modules/vite-plugin-webfont-dl/dist/index.js:19:30)
    at downloadWebfontCss (file:///home/alkaid/source/QSync/node_modules/.pnpm/vite-plugin-webfont-dl@3.6.0_vite@4.0.4/node_modules/vite-plugin-webfont-dl/dist/index.js:431:37) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: 'socks5:',
  expected: 'http:',
  operator: '=='
}

Node.js v19.6.0
```

**Comment by Discreater** [comment]
I found it may caused by axios. Sorry for this issue.
